[package]
name    = "dw3000"
description = "A driver for DW3000 Ultra Wide Band module implementing low and high level"
version = "0.1.3"
authors = ["Clement Pene <clement.pene@sii.fr>", "Romain Saboret <romain.saboret@sii.fr>"]
edition = "2021"
license = "0BSD"

[dependencies]
byte         = "0.2.4"
embedded-hal = "0.2.4"
ieee802154   = "0.5.0"
nb           = "1.0.0"
fixed        = "1.7.0"
micromath    = "2.0.0"

[dependencies.serde]
version = "1.0.125"
default-features = false
features = ["derive"]

[dependencies.ssmarshal]
version = "1.0.0"
default-features = false

[dependencies.num_enum]
version = "0.5.1"
default-features = false

[features]
default = []
std = ["ssmarshal/std", "serde/std", "num_enum/std"]

[workspace]
members = ["stm32f1", "raspberry"]