# Github Actions CI
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    # Cargo test
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Run tests
              run: cargo test --all

    # Clippy
    clippy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Run clippy
              run: cargo clippy --all -- -D warnings
