name: Rust

on:
  push:
    branches: [ "RUST" ]
  pull_request:
    branches: [ "RUST" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose

  # Clippy
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy --all -- -D warnings
